### PR TITLE
Backend initial commit

### PR DESCRIPTION
**Pull request by oneebkhan**
Starting work on the backend, completed the surah collection and added some fields to the user collection. Also includes commits for code refactor in the frontend repo

### CODE REVIEW

**Comment by MuhammadSaadSiddique** [comment]
is it final now

**Comment by oneebkhan** [comment]
Yep, need to create the rest of the models and then create an API for adding patterns. The we can start the main work on the frontend

**Comment by MuhammadSaadSiddique** [comment]
let me help you in flask.

**Comment by oneebkhan** [comment]
Sure, currently we just need to define the models. The columns would be the ones you defined in the mock database in the backend channel

**Pull request merged**
